# Generated by Django 5.2.7 on 2026-05-13 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('yearsExperience', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('cardio', 'cardio'), ('strength', 'strength'), ('yoga', 'yoga'), ('HIIT', 'HIIT'), ('pilates', 'pilates'), ('crossfit', 'crossfit'), ('stretching', 'stretching')], max_length=20)),
                ('level', models.CharField(choices=[('beginer', 'beginer'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=20)),
                ('duration', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('price', models.FloatField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitness.trainer')),
            ],
        ),
    ]
