# Generated by Django 6.0.5 on 2026-05-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='media/')),
                ('imbd', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('productionHouse', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('SCIFI', 'Sci-Fi'), ('DOCUMENTARY', 'Documentary'), ('ANIMATION', 'Animation')], max_length=20)),
                ('format', models.CharField(choices=[('DIGITAL', 'Digital'), ('BLUERAY', 'Blu-ray'), ('DVD', 'DVD')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
    ]
