# Generated by Django 6.0.5 on 2026-05-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='productionHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.productionhouse'),
        ),
    ]
