# Generated by Django 6.0.3 on 2026-05-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_cake_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
