# Generated by Django 6.0.3 on 2026-05-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='onOpenSky',
            field=models.BooleanField(default=None),
        ),
    ]
