# Generated by Django 6.0.3 on 2026-05-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0002_event_date_event_onopensky'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bands',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
