# Generated by Django 6.0.3 on 2026-05-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together={('book', 'author')},
        ),
    ]
