# Generated by Django 4.2.21 on 2025-05-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('cardiologist', 'Cardiology'), ('dermatologist', 'Dermatology'), ('neurologist', 'Neurology')], max_length=20),
        ),
    ]
