# Generated by Django 6.0.3 on 2026-05-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_touristguide_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristguide',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='place',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
