# Generated by Django 6.0.3 on 2026-05-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealExtateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='characteristics',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
